before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y

install:
  - sudo apt-get update -y
  - sudo apt-get install ubuntu-sdk elfutils libelf-dev freeglut3 freeglut3-dev gcc-avr binutils-avr avr-libc gdb-avr cmake -y

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
