before_install:
  - sudo add-apt-repository ppa:leppa/qt5-gles2 -y

install:
  - sudo apt-get update -y
  - sudo apt-get install qtchooser qtbase5-dev elfutils libelf-dev freeglut3 freeglut3-dev gcc-avr binutils-avr avr-libc gdb-avr -y

script:
  - git submodule init
  - git submodule update
  - make -C include/simavr
  - qmake ess.pro
  - make
