before_install:
  - sudo add-apt-repository ppa:leppa/qt5-gles2 -y

install:
  - sudo apt-get update -y
  - sudo apt-get install qtbase5-dev libelf1 freeglut3 avr-libc -y

script:
  - git submodule init
  - git submodule update
  - make -C include/simavr
  - qmake ess.pro
  - make
