before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev qt5-qmake libelf1 freeglut3 avr-libc

script:
  - git submodule init
  - git submodule update
  - make -C include/simavr
  - qmake ess.pro
  - make
