install:
  - yes | sudo add-apt-repository ppa:leppa/qt5-gles2
  - sudo apt-get update
  - sudo apt-get install qtbase-opensource-src libelf1 freeglut3 avr-libc

script:
  - git submodule init
  - git submodule update
  - make -C include/simavr
  - qmake ess.pro
  - make
