before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y

install:
  - sudo apt-get update -y
  - sudo apt-get install ubuntu-sdk elfutils libelf-dev freeglut3 freeglut3-dev gcc-avr binutils-avr avr-libc gdb-avr -y

script:
  - git submodule init
  - git submodule update
  - make -C include/simavr
  - qmake ess.pro
  - make
